import { compile } from 'json-schema-to-typescript';
import { dirname, join } from 'node:path';
import { TapError } from '../client/errors';
import type {
  CredentialField,
  ExtensionManifest,
  JsonSchema,
} from '../manifest/types';

export const GENERATED_HEADER = `/* eslint-disable */
/**
 * Generated by \`tappify extension types\`. Do not edit by hand.
 * Re-run the command after changing tappify.extension.json or any schema it points at.
 */`;

export interface RegistrySnapshot {
  events: { name: string; payload?: JsonSchema }[];
}

export interface GenerateTypesOptions {
  manifest: ExtensionManifest;
  registrySnapshot?: RegistrySnapshot;
  readSchemaFile?(path: string): JsonSchema;
  /**
   * The extension root. A `$ref` inside a schema file resolves against that
   * file's own directory under it, the way the host and the Tap Store read
   * it; without a root the process directory stands in.
   */
  cwd?: string;
}

const STYLE = {
  bracketSpacing: true,
  printWidth: 80,
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
} as const;

function pascal(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(part => part !== '')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

interface Emitter {
  declare(preferredName: string, schema: JsonSchema): Promise<string>;
  declarations(): string[];
}

interface ResolvedSchema {
  schema: JsonSchema;
  /** Where the schema's own nested `$ref`s resolve from. */
  cwd?: string;
}

function createEmitter(
  resolveSchema: (schema: JsonSchema) => ResolvedSchema,
): Emitter {
  const used = new Set<string>();
  const blocks: string[] = [];

  return {
    async declare(preferredName, schema) {
      let name = pascal(preferredName);
      let suffix = 2;
      while (used.has(name)) {
        name = `${pascal(preferredName)}${String(suffix)}`;
        suffix += 1;
      }
      used.add(name);

      const resolved = resolveSchema(schema);
      const input: Parameters<typeof compile>[0] = {
        ...resolved.schema,
        title: name,
      };

      const text = await compile(input, name, {
        bannerComment: '',
        additionalProperties: false,
        declareExternallyReferenced: true,
        enableConstEnums: false,
        format: true,
        style: STYLE,
        unknownAny: true,
        ...(resolved.cwd === undefined ? {} : { cwd: resolved.cwd }),
      });

      blocks.push(text.trim());
      return name;
    },
    declarations() {
      return blocks;
    },
  };
}

function credentialSchema(fields: CredentialField[]): JsonSchema {
  const properties: Record<string, JsonSchema> = {};
  const required: string[] = [];

  for (const field of fields) {
    const property: JsonSchema =
      field.type === 'select' && field.options
        ? { type: 'string', enum: field.options }
        : { type: 'string' };
    if (field.help !== undefined) property.description = field.help;
    properties[field.name] = property;
    if (field.required) required.push(field.name);
  }

  return { type: 'object', properties, required, additionalProperties: false };
}

export async function generateTypes(
  options: GenerateTypesOptions,
): Promise<string> {
  const { manifest, registrySnapshot } = options;
  const contributes = manifest.contributes;

  const resolveSchema = (schema: JsonSchema): ResolvedSchema => {
    const ref = schema.$ref;
    if (typeof ref !== 'string' || ref.startsWith('#')) {
      return { schema, cwd: options.cwd };
    }
    if (options.readSchemaFile === undefined) {
      throw new TapError(
        'TAP_SCHEMA_UNRESOLVED',
        `The manifest points at the schema file "${ref}", but this call passed no readSchemaFile. Run \`tappify extension types\`, which reads schema files from the extension directory, or supply readSchemaFile.`,
      );
    }
    return {
      schema: options.readSchemaFile(ref),
      cwd:
        options.cwd === undefined ? undefined : dirname(join(options.cwd, ref)),
    };
  };

  const emitter = createEmitter(resolveSchema);
  const augmentations: string[] = [];

  const storageEntries = Object.entries(contributes.storage ?? {});
  if (storageEntries.length > 0) {
    const lines: string[] = [];
    for (const [name, collection] of storageEntries) {
      const typeName = await emitter.declare(name, collection.schema);
      const kind = collection.singleton === true ? 'singleton' : 'collection';
      lines.push(
        `    '${name}': { kind: '${kind}'; scope: '${collection.scope}'; document: ${typeName} };`,
      );
    }
    augmentations.push(`  interface TapStorageMap {\n${lines.join('\n')}\n  }`);
  }

  const procedureEntries = Object.entries(manifest.server?.procedures ?? {});
  if (procedureEntries.length > 0) {
    const lines: string[] = [];
    for (const [name, declaration] of procedureEntries) {
      const inputName = await emitter.declare(
        `${name}Input`,
        declaration.input,
      );
      const outputName = await emitter.declare(
        `${name}Output`,
        declaration.output,
      );
      lines.push(
        `    '${name}': { input: ${inputName}; output: ${outputName} };`,
      );
    }
    augmentations.push(
      `  interface TapProcedureMap {\n${lines.join('\n')}\n  }`,
    );
  }

  const actions = contributes.ai?.actions ?? [];
  if (actions.length > 0) {
    const lines: string[] = [];
    for (const action of actions) {
      const name = await emitter.declare(`${action.id}Input`, action.input);
      lines.push(`    '${action.id}': { input: ${name} };`);
    }
    augmentations.push(`  interface TapActionMap {\n${lines.join('\n')}\n  }`);
  }

  const tools = contributes.ai?.tools ?? [];
  if (tools.length > 0) {
    const lines: string[] = [];
    for (const tool of tools) {
      const name = await emitter.declare(`${tool.id}Input`, tool.input);
      lines.push(`    '${tool.id}': { input: ${name} };`);
    }
    augmentations.push(`  interface TapToolMap {\n${lines.join('\n')}\n  }`);
  }

  const prompts = (contributes.ai?.prompts ?? []).filter(
    prompt => prompt.input !== undefined,
  );
  if (prompts.length > 0) {
    const lines: string[] = [];
    for (const prompt of prompts) {
      const name = await emitter.declare(
        `${prompt.id}PromptInput`,
        prompt.input ?? { type: 'object' },
      );
      lines.push(`    '${prompt.id}': { input: ${name} };`);
    }
    augmentations.push(`  interface TapPromptMap {\n${lines.join('\n')}\n  }`);
  }

  const webhooks = contributes.webhooks ?? [];
  if (webhooks.length > 0) {
    const lines: string[] = [];
    for (const webhook of webhooks) {
      const name = await emitter.declare(
        `${webhook.event}Payload`,
        webhook.payload,
      );
      lines.push(`    '${webhook.event}': ${name};`);
    }
    augmentations.push(`  interface TapWebhookMap {\n${lines.join('\n')}\n  }`);
  }

  if (registrySnapshot !== undefined && registrySnapshot.events.length > 0) {
    const lines: string[] = [];
    for (const event of registrySnapshot.events) {
      const name = await emitter.declare(
        `${event.name}Event`,
        event.payload ?? { type: 'object' },
      );
      lines.push(`    '${event.name}': ${name};`);
    }
    augmentations.push(
      `  interface TapHostEventMap {\n${lines.join('\n')}\n  }`,
    );
  }

  const telemetry = manifest.telemetry ?? [];
  if (telemetry.length > 0) {
    const lines = telemetry.map(name => `    '${name}': true;`);
    augmentations.push(
      `  interface TapTelemetryEvents {\n${lines.join('\n')}\n  }`,
    );
  }

  if (contributes.settings) {
    const name = await emitter.declare('Settings', contributes.settings.schema);
    augmentations.push(`  interface TapSettings extends ${name} {}`);
  }

  const credentialFields = contributes.connector?.auth?.fields ?? [];
  if (credentialFields.length > 0) {
    const name = await emitter.declare(
      'Credentials',
      credentialSchema(credentialFields),
    );
    augmentations.push(`  interface TapCredentials extends ${name} {}`);
  }

  const declarations = emitter.declarations();
  const module =
    augmentations.length === 0
      ? "declare module '@tappify/extension-sdk' {}"
      : `declare module '@tappify/extension-sdk' {\n${augmentations.join('\n\n')}\n}`;

  return [
    GENERATED_HEADER,
    '',
    ...(declarations.length > 0 ? [declarations.join('\n\n'), ''] : []),
    module,
    '',
    'export {};',
    '',
  ].join('\n');
}
